name: context
on: push
jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: Describe run
        run: |
          echo "Repository name: ${{ github.repository }}"
          echo "Branch name: ${{ github.ref }}"
          echo "Commit is : ${{ github.sha }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Runner os : ${{ runner.os }}"
