name: FirstRun-1
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v4
      - name: Greeting message
        run: echo "Greeting ...."
