name: Inspect
on: push
jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v4
      - name: List Files & kernel details
        run: |
          echo "===Kernel Details==="
          uname -a
          echo "===List files==="
          ls -larth
      - name: File counts
        run: |
          echo "===File counts==="
          ls -larth | wc -l
